version: '2'

services:
  ll-es:
    container_name: ll-es
    build:
      dockerfile: elasticsearch.Dockerfile
      context: ./elasticsearch
    ports: 
      - "9200:9200"
      - "9300:9300"
  nodejs:
    container_name: nodejs
    build:
      dockerfile: nodejs.Dockerfile
      context: ./nodejs
    ports: 
      - "80:80"
    depends_on:
      - ll-es      
  indexer:
    container_name: indexer
    build: 
      dockerfile: indexer.Dockerfile
      context: ./indexer
    volumes:
      - ./indexer:/indexer
    command: bash -c 'python /indexer/index.py setup && python /indexer/index.py index \\form1\FORMARKIV\LinkLives\LL_v0.2.db'
    depends_on:
      - ll-es
    links:
      - ll-es